"use client";

import { useEffect, useState } from "react";
import { useAuth } from "@/hooks/useAuth";
import axiosInstance from "@/lib/axios";

interface Session { id: string; device: string; ipAddress: string; createdAt: string; lastActiveAt: string; current: boolean }
interface Activity { type: string; success: boolean; device: string; ipAddress: string; createdAt: string }
interface Alert { type: string; message: string; createdAt: string }

export default function SecurityPage() {
  const { isLoggedIn, isLoading } = useAuth(); const [sessions, setSessions] = useState<Session[]>([]); const [activity, setActivity] = useState<Activity[]>([]); const [alerts, setAlerts] = useState<Alert[]>([]); const [error, setError] = useState("");
  useEffect(() => { if (!isLoggedIn) return; axiosInstance.get("/api/auth/security").then(({ data }) => { setSessions(data.sessions); setActivity(data.activityHistory); setAlerts(data.securityAlerts); }).catch(() => setError("Unable to load security information.")); }, [isLoggedIn]);
  const terminate = async (id: string) => { try { await axiosInstance.delete(`/api/auth/sessions/${id}`); setSessions((items) => items.filter((item) => item.id !== id)); } catch { setError("Unable to terminate that session."); } };
  if (isLoading || !isLoggedIn) return <main className="mx-auto max-w-5xl px-4 py-12"><p className="text-slate-600">Sign in to manage account security.</p></main>;
  return <main className="mx-auto max-w-5xl px-4 py-10"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-blue-700">Account security</p><h1 className="mt-2 text-3xl font-bold text-slate-950">Sessions and activity</h1><p className="mt-2 text-slate-600">Review access to your account and terminate anything unfamiliar.</p></div>{error && <p className="mt-5 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<section className="mt-8 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-bold text-slate-950">Active sessions</h2><div className="mt-4 divide-y divide-slate-100">{sessions.map((session) => <div key={session.id} className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold text-slate-900">{session.device} {session.current && <span className="ml-2 text-xs text-emerald-700">Current</span>}</p><p className="mt-1 text-xs text-slate-500">{session.ipAddress} · Last active {new Date(session.lastActiveAt).toLocaleString()}</p></div><button onClick={() => terminate(session.id)} className="self-start rounded-lg border border-slate-300 px-3 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-50">Terminate</button></div>)}</div></section><div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-bold text-slate-950">Security alerts</h2>{alerts.length === 0 ? <p className="mt-4 text-sm text-slate-500">No security alerts.</p> : alerts.slice(0, 10).map((alert) => <div key={alert.createdAt + alert.type} className="mt-4 border-l-2 border-amber-400 pl-3"><p className="text-sm text-slate-800">{alert.message}</p><p className="mt-1 text-xs text-slate-500">{new Date(alert.createdAt).toLocaleString()}</p></div>)}</section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-bold text-slate-950">Login history</h2>{activity.filter((item) => item.type === "login").slice(0, 10).map((item) => <div key={item.createdAt + item.ipAddress} className="mt-4 flex items-start justify-between gap-3"><div><p className="text-sm font-semibold text-slate-800">{item.success ? "Successful login" : "Failed login"}</p><p className="mt-1 text-xs text-slate-500">{item.device} · {item.ipAddress}</p></div><time className="text-right text-xs text-slate-500">{new Date(item.createdAt).toLocaleString()}</time></div>)}</section></div></main>;
}
